apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  labels:
    testing.upbound.io/example-name: s3
  name: nahmed-sbox-cxp-test
spec:
  providerConfigRef:
    name: provider-aws
  forProvider:
    objectLockEnabled: true
    region: us-west-1
    tags:
      Name: nahmed-sbox-cxp-test
