apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  name: nahmed-sbox-cxp-s3-test
  namespace: crossplane-system
spec:
  forProvider:
    region: us-west-1
  providerConfigRef:
    name: provider-aws
